version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx2048m
      JAVA_OPTS: -Xms518m -Xmx2048m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "SwrveConversationSDK/build.gradle" }}-{{ checksum "SwrveSDK/build.gradle" }}-{{ checksum "SwrveSDKCommon/build.gradle" }}-{{ checksum "SwrveSDKTest/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "SwrveConversationSDK/build.gradle" }}-{{ checksum "SwrveSDK/build.gradle" }}-{{ checksum "SwrveSDKCommon/build.gradle" }}-{{ checksum "SwrveSDKTest/build.gradle" }}
      - run:
          name: Build and Test
          command: CIRCLE_CI=1 ./gradlew build test
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: SwrveSDKTest/build/test-results

# See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
