plugins {
    id 'com.android.library'
    id 'maven-publish'
    id 'signing'
    id 'tech.yanand.maven-central-publish' version '1.3.0'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.swrve.swrvesdkcommon'
    compileSdk Integer.parseInt(project.ANDROID_BUILD_SDK_VERSION)

    defaultConfig {
        minSdkVersion Integer.parseInt(project.ANDROID_BUILD_MIN_SDK_VERSION)
        targetSdkVersion Integer.parseInt(project.ANDROID_BUILD_TARGET_SDK_VERSION)
        consumerProguardFiles 'proguard-rules.pro'
    }

    buildTypes {
        release {}
        debug {}
    }

    lintOptions {
        abortOnError true
        baseline file("../lint/lint-baseline-swrvesdkcommon.xml")
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
}

dependencies {
    implementation 'com.google.code.gson:gson:' + project.GSON_VERSION
    implementation 'androidx.appcompat:appcompat:' + project.ANDROIDX_APPCOMPAT_VERSION
    implementation 'com.jakewharton.timber:timber:' + project.TIMBER_VERSION
    implementation 'androidx.work:work-runtime:' + project.ANDROIDX_WORK_RUNTIME_VERSION
//    implementation 'androidx.core:core-ktx:1.17.0'
}

apply from: "build-maven-publish.gradle"
