# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value- -Xmx10248m
# http-//stackoverflow.com/questions/17012619/android-studio-gradle-issue-outofmemoryerror-permgen-space
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+IgnoreUnrecognizedVMOptions

android.useAndroidX=true
