task androidCoreJavadoc(type: Javadoc, dependsOn: "assembleCoreRelease") {
    description "Generates Javadoc for Core release."
    destinationDir = layout.buildDirectory.dir("docs/javadoc_core").get().asFile
    failOnError true
    include 'com/swrve/**'
    
    doFirst {
        source = android.sourceSets.main.java.srcDirs + android.sourceSets.core.java.srcDirs
        classpath += files(android.bootClasspath)
        classpath += configurations.coreReleaseCompileClasspath
    }
}
task androidCoreJavadocsJar(type: Jar) {
    description "Package Javadoc for Core."
    mustRunAfter("androidCoreJavadoc")
    archiveClassifier = 'javadoc'
    from androidCoreJavadoc
}
task androidCoreSourcesJar(type: Jar) {
    description "Package sources for Core."
    archiveClassifier = 'sources'
    from files(android.sourceSets.main.java.srcDirs) + files(android.sourceSets.core.java.srcDirs)
}

task androidFirebaseJavadoc(type: Javadoc, dependsOn: "assembleFirebaseRelease") {
    description "Generates Javadoc for Firebase release."
    destinationDir = layout.buildDirectory.dir("docs/javadoc_firebase").get().asFile
    failOnError true
    include 'com/swrve/**'
    
    doFirst {
        source = android.sourceSets.main.java.srcDirs + android.sourceSets.firebase.java.srcDirs
        classpath += files(android.bootClasspath)
        classpath += configurations.firebaseReleaseCompileClasspath
    }
}
task androidFirebaseJavadocsJar(type: Jar) {
    description "Package Javadoc for Firebase."
    mustRunAfter("androidFirebaseJavadoc")
    archiveClassifier = 'javadoc'
    from androidFirebaseJavadoc
}
task androidFirebaseSourcesJar(type: Jar) {
    description "Package sources for Firebase."
    archiveClassifier = 'sources'
    from files(android.sourceSets.main.java.srcDirs) + files(android.sourceSets.firebase.java.srcDirs)
}

task androidHuaweiJavadoc(type: Javadoc, dependsOn: "assembleHuaweiRelease") {
    description "Generates Javadoc for Huawei release."
    destinationDir = layout.buildDirectory.dir("docs/javadoc_huawei").get().asFile
    failOnError true
    include 'com/swrve/**'
    
    doFirst {
        source = android.sourceSets.main.java.srcDirs + android.sourceSets.huawei.java.srcDirs
        classpath += files(android.bootClasspath)
        classpath += configurations.huaweiReleaseCompileClasspath
    }
}
task androidHuaweiJavadocsJar(type: Jar) {
    description "Package Javadoc for Huawei."
    mustRunAfter("androidHuaweiJavadoc")
    archiveClassifier = 'javadoc'
    from androidHuaweiJavadoc
}
task androidHuaweiSourcesJar(type: Jar) {
    description "Package sources for Huawei."
    archiveClassifier = 'sources'
    from files(android.sourceSets.main.java.srcDirs) + files(android.sourceSets.huawei.java.srcDirs)
}

tasks.withType(Javadoc) {
    options.addStringOption('Xdoclint:none', '-quiet')
}

publishing {
    publications {
        core(MavenPublication) {
            artifactId project.SWRVE_CORE_ARTIFACT_ID
            groupId project.SWRVE_GROUP_ID
            version project.SWRVE_SDK_VERSION
            artifacts = [androidCoreJavadocsJar, "$buildDir/outputs/aar/${project.name}-core-release.aar", androidCoreSourcesJar]

            // The publication doesn't know about our dependencies due to components.java not being present in aar pieces
            // so we have to manually add them to the pom
            pom.withXml {
                def root = asNode()
                root.appendNode('name', 'SwrveSDK - Core')
                root.appendNode('description', 'SwrveSDK Core is the SwrveSDK Core flavor')
                root.appendNode('url', 'https://github.com/Swrve/swrve-android-sdk')

                def dependenciesNode = root.appendNode('dependencies')
                //Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
                configurations.getByName("coreReleaseCompileClasspath").allDependencies.each {
                    if (it.group == null || it.name == null || it.version == null) {
                        logger.log(LogLevel.ERROR, "Invalid dependency")
                    } else {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        if (it.name == 'SwrveSDKCommon') {
                            dependencyNode.appendNode('groupId', project.SWRVE_GROUP_ID)
                            dependencyNode.appendNode('artifactId', project.SWRVE_COMMON_ARTIFACT_ID)
                            dependencyNode.appendNode('version', project.SWRVE_SDK_VERSION)
                            dependencyNode.appendNode('scope', 'compile')
                        } else {
                            dependencyNode.appendNode('groupId', it.group)
                            dependencyNode.appendNode('artifactId', it.name)
                            dependencyNode.appendNode('version', it.version)
                            dependencyNode.appendNode('scope', 'compile')
                        }
                    }
                }

                def scm = root.appendNode('scm')
                scm.appendNode('url', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('connection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('developerConnection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')

                def license = root.appendNode('licenses').appendNode('license')
                license.appendNode('name', 'The Apache Software License, Version 2.0')
                license.appendNode('url', 'http://www.apache.org/licenses/LICENSE-2.0.txt')

                def developer = root.appendNode('developers').appendNode('developer')
                developer.appendNode('id', 'sdkdev')
                developer.appendNode('name', 'Swrve SDK Developer')
            }
        }
        firebase(MavenPublication) {
            artifactId project.SWRVE_FIREBASE_ARTIFACT_ID
            groupId project.SWRVE_GROUP_ID
            version project.SWRVE_SDK_VERSION
            artifacts = [androidFirebaseJavadocsJar, "$buildDir/outputs/aar/${project.name}-firebase-release.aar", androidFirebaseSourcesJar]

            // The publication doesn't know about our dependencies due to components.java not being present in aar pieces
            // so we have to manually add them to the pom
            pom.withXml {
                def root = asNode()
                root.appendNode('name', 'SwrveSDK - Firebase')
                root.appendNode('description', 'SwrveSDK Firebase is the SwrveSDK Firebase flavor')
                root.appendNode('url', 'https://github.com/Swrve/swrve-android-sdk')

                def dependenciesNode = root.appendNode('dependencies')
                //Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
                configurations.getByName("firebaseReleaseCompileClasspath").allDependencies.each {
                    if (it.group == null || it.name == null || it.version == null) {
                        logger.log(LogLevel.ERROR, "Invalid dependency")
                    } else {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        if (it.name == 'SwrveSDKCommon') {
                            dependencyNode.appendNode('groupId', project.SWRVE_GROUP_ID)
                            dependencyNode.appendNode('artifactId', project.SWRVE_COMMON_ARTIFACT_ID)
                            dependencyNode.appendNode('version', project.SWRVE_SDK_VERSION)
                            dependencyNode.appendNode('scope', 'compile')
                        } else {
                            dependencyNode.appendNode('groupId', it.group)
                            dependencyNode.appendNode('artifactId', it.name)
                            dependencyNode.appendNode('version', it.version)
                            dependencyNode.appendNode('scope', 'compile')
                        }
                    }
                }

                def scm = root.appendNode('scm')
                scm.appendNode('url', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('connection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('developerConnection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')

                def license = root.appendNode('licenses').appendNode('license')
                license.appendNode('name', 'The Apache Software License, Version 2.0')
                license.appendNode('url', 'http://www.apache.org/licenses/LICENSE-2.0.txt')

                def developer = root.appendNode('developers').appendNode('developer')
                developer.appendNode('id', 'sdkdev')
                developer.appendNode('name', 'Swrve SDK Developer')
            }
        }
        huawei(MavenPublication) {
            artifactId project.SWRVE_HUAWEI_ARTIFACT_ID
            groupId project.SWRVE_GROUP_ID
            version project.SWRVE_SDK_VERSION
            artifacts = [androidHuaweiJavadocsJar, "$buildDir/outputs/aar/${project.name}-huawei-release.aar", androidHuaweiSourcesJar]

            // The publication doesn't know about our dependencies due to components.java not being present in aar pieces
            // so we have to manually add them to the pom
            pom.withXml {
                def root = asNode()
                root.appendNode('name', 'SwrveSDK - Huawei')
                root.appendNode('description', 'SwrveSDK Huawei is the SwrveSDK Huawei flavor')
                root.appendNode('url', 'https://github.com/Swrve/swrve-android-sdk')

                def dependenciesNode = root.appendNode('dependencies')
                //Iterate over the compile dependencies (we don't want the test ones), adding a <dependency> node for each
                configurations.getByName("huaweiReleaseCompileClasspath").allDependencies.each {
                    if (it.group == null || it.name == null || it.version == null) {
                        logger.log(LogLevel.ERROR, "Invalid dependency")
                    } else {
                        def dependencyNode = dependenciesNode.appendNode('dependency')
                        if (it.name == 'SwrveSDKCommon') {
                            dependencyNode.appendNode('groupId', project.SWRVE_GROUP_ID)
                            dependencyNode.appendNode('artifactId', project.SWRVE_COMMON_ARTIFACT_ID)
                            dependencyNode.appendNode('version', project.SWRVE_SDK_VERSION)
                            dependencyNode.appendNode('scope', 'compile')
                        } else {
                            dependencyNode.appendNode('groupId', it.group)
                            dependencyNode.appendNode('artifactId', it.name)
                            dependencyNode.appendNode('version', it.version)
                            dependencyNode.appendNode('scope', 'compile')
                        }
                    }
                }

                def scm = root.appendNode('scm')
                scm.appendNode('url', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('connection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')
                scm.appendNode('developerConnection', 'scm:git@github.com:Swrve/swrve-android-sdk.git')

                def license = root.appendNode('licenses').appendNode('license')
                license.appendNode('name', 'The Apache Software License, Version 2.0')
                license.appendNode('url', 'http://www.apache.org/licenses/LICENSE-2.0.txt')

                def developer = root.appendNode('developers').appendNode('developer')
                developer.appendNode('id', 'sdkdev')
                developer.appendNode('name', 'Swrve SDK Developer')
            }
        }
    }

    repositories {
        maven {
            url = layout.buildDirectory.dir("../publish").get().asFile.toURI()
        }
    }
}

String isSignAndroidRelease = System.getenv('SIGN_ANDROID_RELEASE')
if (isSignAndroidRelease != null && isSignAndroidRelease.toBoolean()) {
    project.logger.lifecycle('Swrve: signing publishing.publications. Ensure env variables are set and gpg file in place')
    project.ext['signing.keyId'] = System.getenv('GPG_KEY_ID')
    project.ext['signing.password'] = System.getenv('GPG_KEY_PASSPHRASE')
    project.ext['signing.secretKeyRingFile'] = System.getenv('GPG_KEYRING_FILE')
    signing {
        sign publishing.publications
    }
    tasks.withType(Sign).configureEach { task ->
        task.dependsOn tasks.withType(Jar)
    }
    tasks.withType(PublishToMavenRepository).configureEach { task ->
        task.dependsOn tasks.withType(Sign)
    }
} else {
    project.logger.lifecycle('Swrve: NOT signing publishing.publications because SIGN_ANDROID_RELEASE is not set')
    tasks.withType(PublishToMavenRepository).configureEach { task ->
        task.dependsOn tasks.withType(Jar)
    }
}

mavenCentral {
    authToken = System.getenv('SONATYPE_MAVEN_CENTRAL_TOKEN')
    publishingType = 'AUTOMATIC'
    maxWait = 300  //  300 = wait for 5 minutes
}
